name: Deploy DEVELOPMENT to Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Set deploy mode environment variable
        run: echo "REACT_APP_ENVIRONMENT=development" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          cd media_commons_booking_app
          npm ci
      - name: Set up clasp authentication
        run: |
          echo "$CLASP_CREDENTIALS" > ~/.clasprc.json
        env:
          CLASP_CREDENTIALS: ${{ secrets.CLASP_CREDENTIALS }}
      - name: Install clasp
        run: npm install -g @google/clasp
      - name: Push to Google Apps Script
        run: |
          cd media_commons_booking_app
          echo "Yes" | npm run deploy
      - name: Create new version and push
        run: |
          cd media_commons_booking_app
          clasp deploy --deploymentId AKfycbxmQf1ZncntQwdIaGq372w5gbdiltLGmzo2xbV7efAbZQ7U7zWtMJBw0EQjnXZm4aYimw -d "DEVELOPMENT"
