name: Unit Tests

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd booking-app
          # Clean install to avoid optional dependencies issues
          rm -rf node_modules package-lock.json
          npm install --force

      - name: Run unit tests
        env:
          # Fix for Rollup optional dependencies issues
          ROLLUP_BINARY_PATH: ""
        run: |
          cd booking-app
          npm run test:unit

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: unit-test-results
          path: |
            booking-app/coverage/
            booking-app/test-results/
          retention-days: 30
