name: Unit Tests

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: booking-app/package-lock.json

      - name: Install dependencies
        run: |
          cd booking-app
          npm ci

      - name: Run unit tests
        run: |
          cd booking-app
          npm run test:unit

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: unit-test-results
          path: |
            booking-app/coverage/
            booking-app/test-results/
          retention-days: 30
